name: 🌐 Web Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes production=yes warnings=extra werror=yes debug_symbols=no use_closure_compiler=yes lto=full
  EM_VERSION: 4.0.11
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-web
  cancel-in-progress: true

jobs:
  web-template:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template w/ threads (target=template_release, threads=yes)
            cache-name: web-template
            target: template_release
            sconsflags: threads=yes production=yes
            tests: false
            artifact: true

          - name: Template w/o threads (target=template_release, threads=no)
            cache-name: web-nothreads-template
            target: template_release
            sconsflags: threads=no production=yes
            tests: false
            artifact: true

    steps:
      - uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          submodules: recursive

      - uses: actions/checkout@v4
        with:
          path: patch
          sparse-checkout: |
            patch.py
          sparse-checkout-cone-mode: false

      - name: Apply Patches
        run: |
          python patch/patch.py

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
          cache-key: emsdk-${{ matrix.cache-name }}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: web
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
